### ISSUE TITLE
Help , HTTP over TCP tunnel

### ISSUE THREAD

**Issue by ingnelson** [2785/fancy-http-client#6]
Hello @2785 

I am from America, is it possible with your knowledge create a HTTP over TCP tunnel to bypass my isp provider , but any data the client need to transfer to the server should be via a new HTTP request ( encode64 ) then server decode the data ?
because my ISP provider blocks the upstream data via HTTP BODY.

It is difficul for me ( i am not a programmer)  and i can not do it. I only have a android app and i capture the data using TCPDUMP , and i found how he do it to bypass the firewall.
i did all the test to check the isp restrictions.

my telegram is : @Trader_Nelson

i will wait your reply.

**Comment by 2785** [comment]
Hey, unfortunately that's out of my knowledge.
